### ISSUE TITLE
Make PDF colourful

### ISSUE THREAD

**Issue by alifeee** [alifeee/json-resume#9]
Currently, the PDF makes all colours black. It would be cool if it did not.

This is because of the [Bootstrap 3](https://getbootstrap.com/docs/3.3/) print media query which conforms printing, and sets all text colours to black:

```css
@media print
  *, ::after, ::before {
    color: #000 !important;
    text-shadow: none !important;
    background: 0 0 !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
  }
```

This is very hard to disable, as this thread attests to:

<https://stackoverflow.com/questions/33410724/bootstrap-print-css-removes-background-color>
